services:
  # FastAPI Backend Service
  - type: web
    name: intellisearch-backend
    env: python
    plan: starter
    buildCommand: "cd web-app/backend && pip install -r requirements.txt"
    startCommand: "cd web-app/backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: SERPER_API_KEY  
        sync: false  # Set manually in Render dashboard
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: "/opt/render/project/src"

  # React Frontend Service  
  - type: web
    name: intellisearch-frontend
    env: node
    plan: starter
    buildCommand: "cd web-app/frontend && npm install && npm run build"
    startCommand: "cd web-app/frontend && npm run preview"
    envVars:
      - key: VITE_API_URL
        value: https://intellisearch-backend.onrender.com
      - key: NODE_ENV
        value: production