services:
  - type: web
    name: intellisearch-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    rootDir: web-app/backend
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
    
  - type: static
    name: intellisearch-frontend
    buildCommand: npm install --legacy-peer-deps && npm run build
    publishPath: ./dist
    rootDir: web-app/frontend
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: intellisearch-backend
          property: host