services:
  - type: web
    name: intellisearch-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
    
  - type: web
    name: intellisearch-frontend
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: intellisearch-backend
          property: host